### ISSUE TITLE
Make pipeline able to use cached mmi file for minimap2

### ISSUE THREAD

**Issue by ssadedin** [bioinfomethods/warpy#1]
Currently each time warpy is run on a new sample it creates a new .mmi file that is 6.8GB in size for the human reference genome.

We should make it possible to use a cached version of this to save space and avoid delay in starting the pipeline.

**Comment by jimmykhchiu** [comment]
Now the .mmi file is only generated when the cached version does not exist under directory `data/hg38` in the pipeline, and the generated one will be cached in the same location.

See this [commit](https://github.com/bioinfomethods/warpy/commit/5fd798b7decffa7aab06eb23e1f001de3e656148) for the code changes.
